name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checking Out
      uses: actions/checkout@v2
      
    - name: Setting up Xcode
      uses: sinoru/actions-setup-xcode@v1.1
      with:
       xcode-version: '11.2.1' # Exact version of a Xcode version to use
       apple-id: 'jonalist@me.com' # Apple ID to download from Apple Developer when Xcode not available in local
       apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
       
    - name : Building ControlRoom
      run: xcodebuild -project ControlRoom.xcodeproj 
      
    - name: Tagging
      uses: Actions-R-Us/actions-tagger@latest
      env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
      
      # This is in the workflow, not on release
    - name: Uploading ControlRoom.app 
      uses: actions/upload-artifact@1.0.0
      with:
        name: ControlRoom.zip  
        path: ./build/Release
        
      # Add Homebrew support later
    - name: Releasing to GH
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: ./build/Release/ControlRoom.app
