name: Build

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Xcode
      uses: sinoru/actions-setup-xcode@v1.1
      with:
       xcode-version: '11.2.1' # Exact version of a Xcode version to use
       apple-id: 'jonalist@me.com' # Apple ID to download from Apple Developer when Xcode not available in local
       apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
       
    - name : Build
      run: xcodebuild -project ControlRoom.xcodeproj 
      
    - name: Upload artifact
      uses: actions/upload-artifact@1.0.0
      with:
        name: ControlRoom.zip  
        path: ./build/Release
        
    - name: Release to GH
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: ./build/Release/ControlRoom.app
