name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checking Out
      uses: actions/checkout@v2
      
    - name: Setting up Xcode
      uses: sinoru/actions-setup-xcode@v1.1
      with:
       xcode-version: '11.2.1' # Exact version of a Xcode version to use
       apple-id: 'jonalist@me.com' # Apple ID to download from Apple Developer when Xcode not available in local
       apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
       
    - name : Building ControlRoom
      run: xcodebuild -project ControlRoom.xcodeproj 
      
      # This is in the workflow, not on release
    - name: Uploading ControlRoom.app 
      uses: actions/upload-artifact@1.0.0
      with:
        name: ControlRoom.zip  
        path: build/Release
      
      # This step is because the next one otherwise would spit all the contents of the .app
    - name: Preparing zip for release
      run: zip build/Release/ControlRoom.zip build/Release -x build/Release/ControlRoom.app.dSYM build/Release/ControlRoom.swiftmodule
    
      # Add Homebrew support later
    - name: Releasing to GH
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: false
        title: Latest ControlRoom
        files: build/Release/ControlRoom.zip
